# docker-compose.yml

version: '3.7'
services:
  url_orm_query_postgres:
    container_name: url_orm_query_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
  url_orm_query_app:
    container_name: url_orm_query_app
    image: test_image
    build:
      context: .
      network: host
    depends_on:
      - url_orm_query_postgres
    volumes:
      - .:/usr/src/app
    command: > 
      sh -c "pnpm run test"
