# docker-compose.yml

version: '3.7'
services:
  postgres:
    container_name: db
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
  app:
    container_name: test
    image: test_image
    build:
      context: .
      network: host
    network_mode: 'host'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: > 
      sh -c "pnpm run test"
